services:
  - type: web
    name: ql-nhathuoc
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Infobip__ApiKey
        sync: false
      - key: Infobip__SecretKey
        sync: false
      - key: BankInfo__AccountNo
        sync: false
    autoDeploy: true
